<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Profil Mahasiswa') }}
        </h2>
    </x-slot>

    <div class="py-12 bg-slate-100 dark:bg-slate-900 min-h-screen">
        <div class="max-w-3xl mx-auto sm:px-6 lg:px-8">
            
            <div class="bg-white dark:bg-gray-800 shadow-2xl rounded-3xl overflow-hidden border border-gray-200 dark:border-gray-700">
                
                <div class="bg-indigo-600 px-8 py-10 text-center">
                    <div class="inline-flex items-center justify-center h-24 w-24 rounded-full bg-white text-indigo-600 text-4xl font-black mb-4 shadow-lg">
                        {{ substr($data->nama, 0, 1) }}
                    </div>
                    <h1 class="text-2xl font-bold text-white uppercase tracking-tight">{{ $data->nama }}</h1>
                    <p class="text-indigo-100 font-medium">{{ $data->prodi }}</p>
                </div>

                <div class="p-8 md:p-10">
                    <div class="grid grid-cols-1 gap-6">
                        
                        <div class="flex items-center p-4 bg-gray-50 dark:bg-gray-700/50 rounded-2xl border border-gray-100 dark:border-gray-600">
                            <div class="bg-indigo-100 dark:bg-indigo-900 p-3 rounded-xl mr-4">
                                <svg class="w-6 h-6 text-indigo-600 dark:text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V8a2 2 0 00-2-2h-5m-4 0V5a2 2 0 114 0v1m-4 0a2 2 0 104 0m-5 8a2 2 0 100-4 2 2 0 000 4zm0 0c1.306 0 2.417.835 2.83 2M9 14a3.001 3.001 0 00-2.83 2M15 11h3m-3 4h2"></path></svg>
                            </div>
                            <div>
                                <p class="text-xs font-bold text-gray-400 uppercase">Nomor Induk Mahasiswa</p>
                                <p class="text-lg font-bold text-gray-800 dark:text-gray-100">{{ $data->nim }}</p>
                            </div>
                        </div>

                        <div class="flex items-center p-4 bg-gray-50 dark:bg-gray-700/50 rounded-2xl border border-gray-100 dark:border-gray-600">
                            <div class="bg-purple-100 dark:bg-purple-900 p-3 rounded-xl mr-4">
                                <svg class="w-6 h-6 text-purple-600 dark:text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                            </div>
                            <div>
                                <p class="text-xs font-bold text-gray-400 uppercase">Hobi / Minat</p>
                                <p class="text-lg font-bold text-gray-800 dark:text-gray-100">{{ $data->hobi }}</p>
                            </div>
                        </div>

                    </div>

                    <div class="mt-10 flex flex-col md:flex-row gap-4">
                        <button onclick="window.print()" class="flex-1 bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-6 rounded-xl transition shadow-lg shadow-indigo-200 dark:shadow-none text-center">
                            Cetak Biodata
                        </button>
                        <a href="{{ route('dashboard') }}" class="flex-1 bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 text-gray-700 dark:text-gray-200 font-bold py-3 px-6 rounded-xl text-center hover:bg-gray-50 dark:hover:bg-gray-600 transition">
                            Kembali ke Dashboard
                        </a>
                    </div>
                </div>
            </div>

            <p class="text-center mt-6 text-gray-400 text-xs">Generated by Laravel v{{ Illuminate\Foundation\Application::VERSION }}</p>
        </div>
    </div>
</x-app-layout>